version: '3.4'
services:
  api:
    build: ./bee_build
    image: ${SERVICE_NAME}
    container_name: ${SERVICE_NAME}
    volumes:
      - gosrc:/go
      - .:/go/src/${API_BASE_DIR}/${API_NAME}
    env_file:
      - custom.env
    ports:
      - "${MOVIMIENTOS_CRUD_PORT}:${MOVIMIENTOS_CRUD_PORT}"
    environment:
      - MOVIMIENTOS_CRUD_HTTP_PORT=${MOVIMIENTOS_CRUD_PORT}
      - API_NAME=${API_NAME}
      - MOVIMIENTOS_CRUD_DB_USER=${MOVIMIENTOS_CRUD_DB_USER}
      - MOVIMIENTOS_CRUD_DB_PASS=${MOVIMIENTOS_CRUD_DB_PASS}
      - MOVIMIENTOS_CRUD_DB_HOST=${MOVIMIENTOS_CRUD_DB_HOST}
      - MOVIMIENTOS_CRUD_DB_NAME=${MOVIMIENTOS_CRUD_DB_NAME}
      - MOVIMIENTOS_CRUD_SCHEMA=${MOVIMIENTOS_CRUD_SCHEMA}
      - RUN_MODE=dev
      - SERVICE_TAGS=traefik.enable=true,traefik.frontend.entryPoints=http,traefik.frontend.rule=Host:${SERVICE_NAME}.localhost
    command: sh -c 'cd ${API_BASE_DIR}/${API_NAME};go get -v -u ./...; bee migrate -driver=postgres -conn="postgres://${MOVIMIENTOS_CRUD_DB_USER}:${MOVIMIENTOS_CRUD_DB_PASS}@${MOVIMIENTOS_CRUD_DB_HOST}:5432/${MOVIMIENTOS_CRUD_DB_NAME}?sslmode=disable&search_path=public" || true; bee run -downdoc=true -gendoc=true'
    depends_on:
      - db
    networks:
      - back_end
  db:
    container_name: ${MOVIMIENTOS_CRUD_DB_HOST}
    image: postgres:10-alpine
    ports:
      - "${MOVIMIENTOS_CRUD_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=${MOVIMIENTOS_CRUD_DB_HOST}
      - POSTGRES_DB=${MOVIMIENTOS_CRUD_DB_NAME}
      - POSTGRES_USER=${MOVIMIENTOS_CRUD_DB_USER}
      - POSTGRES_PASSWORD=${MOVIMIENTOS_CRUD_DB_PASS}
    networks:
      - back_end
volumes:
  gosrc:
  postgres_data:
networks:
  back_end:
    external: true