CREATE SCHEMA IF NOT EXISTS movimientos;
ALTER SCHEMA movimientos OWNER TO desarrollooas;
CREATE SEQUENCE movimientos.movimiento_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE OWNED BY NONE;
ALTER SEQUENCE movimientos.movimiento_id_seq OWNER TO desarrollooas;
CREATE TABLE movimientos.movimiento_proceso_externo(id integer NOT NULL DEFAULT nextval('movimientos.movimiento_id_seq'::regclass),tipo_movimiento_id integer NOT NULL,proceso_externo bigint NOT NULL,movimiento_proceso_externo integer,CONSTRAINT pk_movimiento PRIMARY KEY (id));
ALTER TABLE movimientos.movimiento_proceso_externo OWNER TO desarrollooas;
CREATE SEQUENCE movimientos.movimiento_detalle_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE OWNED BY NONE;
ALTER SEQUENCE movimientos.movimiento_detalle_id_seq OWNER TO desarrollooas;
CREATE TABLE movimientos.movimiento_detalle(id integer NOT NULL DEFAULT nextval('movimientos.movimiento_detalle_id_seq'::regclass),movimiento_id bigint NOT NULL,valor numeric(20,7) NOT NULL,fecha_registro date NOT NULL,descripcion character varying,CONSTRAINT pk_movimiento_detalle PRIMARY KEY (id));
ALTER TABLE movimientos.movimiento_detalle OWNER TO desarrollooas;
CREATE SEQUENCE movimientos.tipo_movimiento_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1 NO CYCLE OWNED BY NONE; 
ALTER SEQUENCE movimientos.tipo_movimiento_id_seq OWNER TO desarrollooas;
CREATE TABLE movimientos.tipo_movimiento(id integer NOT NULL DEFAULT nextval('movimientos.tipo_movimiento_id_seq'::regclass),nombre character varying(20) NOT NULL,descripcion character varying,acronimo character varying(10) NOT NULL,CONSTRAINT pk_tipo_movimiento PRIMARY KEY (id));
ALTER TABLE movimientos.tipo_movimiento OWNER TO desarrollooas;
ALTER TABLE movimientos.movimiento_proceso_externo ADD CONSTRAINT fk_movimiento_tipo_movimiento FOREIGN KEY (tipo_movimiento_id)REFERENCES movimientos.tipo_movimiento (id) MATCH FULL ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE movimientos.movimiento_detalle ADD CONSTRAINT fk_movimiento_detalle_movimiento FOREIGN KEY (movimiento_id)REFERENCES movimientos.movimiento_proceso_externo (id) MATCH FULL ON DELETE RESTRICT ON UPDATE RESTRICT;
INSERT INTO movimientos.tipo_movimiento(id, nombre, descripcion, acronimo)VALUES(1, 'Adicion', 'Adicion a una fuente de financiamiento', 'adicion');
INSERT INTO movimientos.tipo_movimiento(id, nombre, descripcion, acronimo)VALUES(2, 'Reducción', 'Reducción a una fuente de financiamiento', 'reduccion');
INSERT INTO movimientos.tipo_movimiento(id, nombre, descripcion, acronimo)VALUES(3, 'Traslado', 'Traslado entre 2 fuentes de financiamiento', 'traslado');
ALTER TABLE movimientos.movimiento_detalle RENAME CONSTRAINT fk_movimiento_detalle_movimiento to fk_movimiento_detalle_movimiento_proceso_externo;
INSERT INTO movimientos.tipo_movimiento (id, nombre, descripcion, acronimo)VALUES (4, 'AsignarFuente', 'Asigna valores de la fuente a sus dependencias de acuerdo a la apropiación del rubro', 'crear_ff');
ALTER TABLE movimientos.movimiento_detalle RENAME COLUMN movimiento_id to movimiento_proceso_externo_id;
INSERT INTO movimientos.tipo_movimiento(id, nombre, descripcion, acronimo)VALUES(5, 'Suspension', 'Suspension a un valor de fuente de financiamiento', 'suspension');
ALTER TABLE movimientos.movimiento_proceso_externo ADD COLUMN activo boolean;
ALTER TABLE movimientos.movimiento_proceso_externo ADD COLUMN fecha_creacion timestamp;
ALTER TABLE movimientos.movimiento_proceso_externo ADD COLUMN fecha_modificacion timestamp;
ALTER TABLE movimientos.tipo_movimiento ADD COLUMN activo boolean;
ALTER TABLE movimientos.tipo_movimiento ADD COLUMN fecha_creacion timestamp;
ALTER TABLE movimientos.tipo_movimiento ADD COLUMN fecha_modificacion timestamp;
ALTER TABLE movimientos.movimiento_detalle ADD COLUMN activo boolean;
ALTER TABLE movimientos.movimiento_detalle ADD COLUMN fecha_creacion timestamp;
ALTER TABLE movimientos.movimiento_detalle ADD COLUMN fecha_modificacion timestamp;
ALTER TABLE movimientos.movimiento_proceso_externo DROP COLUMN IF EXISTS fecha_registro CASCADE;
ALTER TABLE movimientos.movimiento_detalle DROP COLUMN IF EXISTS fecha_registro CASCADE;
INSERT INTO movimientos.tipo_movimiento(id, nombre, descripcion, acronimo)VALUES(6, 'CDP', 'Certificado Disponibilidad Presupuestal', 'cdp'),(7, 'RP', 'Registro Presupuestal', 'rp'),(8, 'Anulación CDP', 'Anulación Certificado Disponibilidad Presupuestal', 'anul_cdp'),(9, 'Anulación RP', 'Anulación Registro Presupuestal', 'anul_rp');
ALTER TABLE movimientos.tipo_movimiento ADD COLUMN parametros json;
UPDATE movimientos.tipo_movimiento SET parametros='{\"CuentaContraCredito\": true, \"TipoMovimientoCuentaCredito\": \"traslado_destino\"}' WHERE acronimo='traslado';
INSERT INTO movimientos.tipo_movimiento(id, nombre, descripcion, acronimo)VALUES(20, 'Adición Fuente', 'Adicion para una Fuente de Financiamiento', 'ad_fuente');
UPDATE movimientos.tipo_movimiento SET parametros='{\"MovOriginRubro\": \"ad_fuente_apropiacion\"}' WHERE acronimo='ad_fuente';
INSERT INTO movimientos.tipo_movimiento(id, nombre, descripcion, acronimo)VALUES(21, 'Reducción Fuente ', 'Reducción para una Fuente de Financiamiento', 'rd_fuente');
UPDATE movimientos.tipo_movimiento SET parametros='{\"MovOriginRubro\": \"rd_fuente_apropiacion\"}' WHERE acronimo='rd_fuente';